### ISSUE TITLE
Can you provide a tutorial on generating Camera Trajectory?

### ISSUE THREAD

**Issue by trouble-maker007** [zhenzhiwang/HumanVid#10]
I have some questions about generating Camera Trajectory data. Can you provide a tutorial on generating Camera Trajectory?

**Comment by zhenzhiwang** [comment]
For using camera parameters in diffusion model, please refer to [CameraCtrl](https://github.com/hehao13/CameraCtrl/tree/main?tab=readme-ov-file). For extracting camera parameters from videos, please refer to DPVO and Driod-SLAM. Our code will be released later.

**Comment by trouble-maker007** [comment]
@zhenzhiwang thanks for quick response. I found that the test script argment --calib has different device, which device is used to generate?
```
python demo.py \
    --imagedir=<path to image directory or video> \
    --calib=<path to calibration file> \
    --viz # enable visualization
    --plot # save trajectory plot
    --save_ply # save point cloud as a .ply file
    --save_trajectory # save the predicted trajectory as .txt in TUM format
    --save_colmap # save point cloud + trajectory in the standard COLMAP text format
```

**Comment by zhenzhiwang** [comment]
We use heuristic intrinsics as our own calib file: assuming the camera is a standard 36mm CMOS full-frame camera, we use 50mm focal length for horizontal videos and 75mm focal length for vertical videos. The numbers are from author's personal observation on pexels videos without any support from quantitative results. Yet it turns out that the heuristic values work well in our experiments.
