### ISSUE TITLE
download scripts

### ISSUE THREAD

**Issue by JoJoistheBestOne** [zhenzhiwang/HumanVid#13]
Hi authors.
could you guys release some scripts for downloading the url, since there is 'Status code: 404' when i try to download via below code.

```
import requests

url='https://www.pexels.com/video/7080900/download'
response = requests.get(url)
print(response.status_code)
```

**Comment by JoJoistheBestOne** [comment]
![image](https://github.com/user-attachments/assets/3aa7d657-8bad-47e0-a363-c9ea41a74b58)

**Comment by wangqiang9** [comment]
I have the same question, get response of `404` or `403`.

**Comment by zhenzhiwang** [comment]
Updates: I find that pexels.com are not denying download from url. They just changed the url address. The old url address just need the information of video id with a 'download', yet it didn't work since yesterday. New urls are specific urls to videos with each resolution. For example, for video 2795749, the old url is `https://www.pexels.com/video/2795749/download`, yet the new url is `https://videos.pexels.com/video-files/2795749/2795749-{resolution}.mp4`, where `resolution` is file names for each resolution, e.g., `uhd_3840_2160_25fps`. 

A little problem with the url convertion is that we could only guess the resolution information. I will try to finish the url convertion today for most of videos in the released urls.

**Comment by zhenzhiwang** [comment]
The new urls are uploaded in the google drive. @wangqiang9 @JoJoistheBestOne
